server:
  port: 7001

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yucg?useSSL=false&characterEncoding=utf8
    username: root
    password: 123456

