server:
  port: 7001

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yucg?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456


mybatis:
  mapper-locations: classpath:mapper/*.xml


upload:
  dir: G:\大学学习资料\实训项目\yucg\User_server\src\main\resources\images
